# Generated by Django 5.2.1 on 2025-05-17 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScamReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("scammer_address", models.CharField(max_length=255)),
                ("reporter_address", models.CharField(max_length=255)),
                (
                    "scam_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("wallet", "Wallet"),
                            ("social_media", "Social Media"),
                            ("smart_contract", "Smart Contract"),
                            ("airdrop", "Airdrop"),
                            ("impersonation", "Impersonation"),
                            ("phishing", "Phishing"),
                            ("fake_token", "Fake Token"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "contact_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("additional_details", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verification_deadline", models.DateTimeField()),
                (
                    "transaction_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sui_object_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stake_amount", models.BigIntegerField(default=0)),
                ("verification_count", models.IntegerField(default=0)),
                ("rejection_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("screenshot", "Screenshot"),
                            ("report", "Report"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="evidence/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("hash", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="core.scamreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScamTactic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scam_tactics",
                        to="core.scamreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("event", models.CharField(max_length=255)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="core.scamreport",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verifier", models.CharField(max_length=255)),
                ("verified", models.BooleanField()),
                ("comment", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "transaction_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="core.scamreport",
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "verifier")},
            },
        ),
    ]
