# Generated by Django 5.2.1 on 2025-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scamreport",
            name="transaction_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
