# Generated by Django 5.2.1 on 2025-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_scamreport_transaction_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="scamreport",
            name="network",
            field=models.CharField(
                blank=True, default="testnet", max_length=25, null=True
            ),
        ),
    ]
